version: '3'
services:
  syslog:
    image: 'docker.elastic.co/logstash/logstash:7.1.1'
    restart: always
    environment:
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/syslog.conf:/usr/share/logstash/pipeline/syslog.conf
    ports:
      - 9002:9002/tcp
      - 9002:9002/udp
    networks:
    - hotspotplusgate
  clickhouse-sinker-syslog:
    image: 'registry.gitlab.com/parmenides/hotspotplus/clickhouse-sinker:latest'
    restart: always
    volumes:
      - ./sinker-syslog:/opt/config
    command: --conf /opt/config
    networks:
     - hotspotplusgate

networks:
  hotspotplusgate:
    external: true
