image: docker:stable

services:
  - docker:dind
stages:
  - api
  - apilicense
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
api:
  stage: api
  script:
    - apk add --no-cache jq curl bash git
    - ./api/build.sh
apilicense:
  stage: apilicense
  script:
    - apk add --no-cache jq curl bash git
    - ./api-license/build.sh
    - ./dashboard/build.sh
    - ./license-dashboard/build.sh
    - ./log-aggregator/build.sh
    - ./log-worker/build.sh
