image: docker:stable

services:
  - docker:dind
stages:
  - build_api
  - build_api_license
  - build_dashboard
  - build_license_dashboard
  - build_log_aggregator
  - build_log_worker
  - build_goflow
  - build_clickhouse_sinker
  - build_coordinator
  - build_hotspot
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
  - apk add --no-cache jq curl bash git
build_api:
  stage: echo $env:CI_JOB_ID && build_api
  when: manual
  only:
    - tags
  script:
    - ./api/build.sh
build_coordinator:
  stage: build_coordinator
  when: manual
  only:
    - tags
  script:
    - ./coordinator/build.sh
build_api_license:
  stage: build_api_license
  when: manual
  only:
    - tags
  script:
    - ./api-license/build.sh
build_dashboard:
  stage: build_dashboard
  when: manual
  only:
    - tags
  script:
    - ./dashboard/build.sh
build_hotspot:
  stage: build_hotspot
  when: manual
  only:
    - tags
  script:
    - ./hotspot/build.sh
build_license_dashboard:
  stage: build_license_dashboard
  when: manual
  only:
    - tags
  script:
    - ./license-dashboard/build.sh
build_log_aggregator:
  stage: build_log_aggregator
  when: manual
  only:
    - tags
  script:
    - ./log-aggregator/build.sh
build_log_worker:
  stage: build_log_worker
  when: manual
  only:
    - tags
  script:
    - ./log-worker/build.sh
build_goflow:
  stage: build_goflow
  when: manual
  script:
    - ./goflow/build.sh
build_clickhouse_sinker:
  stage: build_clickhouse_sinker
  when: manual
  script:
    - ./clickhouse-sinker/build.sh
