image: docker:stable

services:
  - docker:dind
stages:
  - api
  - apilicense
  - dashboard
  - licensedashboard
  - logaggregator
  - logworker
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
  - apk add --no-cache jq curl bash git
api:
  stage: api
  only:
    - tags
  script:
    - ./api/build.sh
apilicense:
  stage: apilicense
  only:
    - tags
  script:
    - ./api-license/build.sh
dashboard:
  stage: dashboard
  only:
    - tags
  script:
    - ./dashboard/build.sh
licensedashboard:
  stage: licensedashboard
  only:
    - tags
  script:
    - ./license-dashboard/build.sh
logaggregator:
  stage: logaggregator
  only:
    - tags
  script:
    - ./log-aggregator/build.sh
logworker:
  stage: logworker
  only:
    - tags
  script:
    - ./log-worker/build.sh
