image: docker:stable

services:
  - docker:dind
stages:
  - build_api
  - build_api_license
  - build_dashboard
  - build_license_dashboard
  - build_log_aggregator
  - build_log_worker
before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY_IMAGE
  - apk add --no-cache jq curl bash git
build_api:
  stage: build_api
  when: manual
  only:
    - tags
  script:
    - ./api/build.sh
build_api_license:
  stage: build_api_license
  when: manual
  only:
    - tags
  script:
    - ./api-license/build.sh
build_dashboard:
  stage: build_dashboard
  when: manual
  only:
    - tags
  script:
    - ./dashboard/build.sh
build_license_dashboard:
  stage: build_license_dashboard
  when: manual
  only:
    - tags
  script:
    - ./license-dashboard/build.sh
build_log_aggregator:
  stage: build_log_aggregator
  when: manual
  only:
    - tags
  script:
    - ./log-aggregator/build.sh
build_log_worker:
  stage: build_log_worker
  when: manual
  only:
    - tags
  script:
    - ./log-worker/build.sh
