version: '3.6'
services:
  hotspotplusapi:
    build:
      context: ${PWD}/api
    user: '${UID:-1000}:${GID:-1000}'
    restart: always
    container_name: apihotspotplus
    command: npm run start:dev
    depends_on:
      - mongodb
      - elasticsearch
      - redis
    env_file:
      - api/.env
    volumes:
      - ${PWD}/systemId:/systemId
      - ${PWD}/api/server/:/usr/src/app/server/
      - ${PWD}/api/common:/usr/src/app/common/
      - ${PWD}/api/logs:/logs
      - ${PWD}/api/key:/key
    networks:
      - hotspotplusgate
  logworker:
    build:
      context: ${PWD}/log-worker
    user: '${UID:-1000}:${GID:-1000}'
    restart: always
    env_file:
      - ${PWD}/log-worker/.env
    command: npm start
    depends_on:
      - kafka
      - redis
    volumes:
      - ${PWD}/log-worker/modules/:/usr/src/app/modules/
      - ${PWD}/log-worker/index.js:/usr/src/app/index.js
      - ${PWD}/log-worker/logs:/logs
    networks:
      - hotspotplusgate
  logaggregator:
    build:
      context: ${PWD}/log-aggregator
    user: '${UID:-1000}:${GID:-1000}'
    restart: always
    command: npm start
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ${PWD}/log-aggregator/.env
    volumes:
      - ${PWD}/log-aggregator/modules/:/usr/src/app/modules/
      - ${PWD}/log-aggregator/index.js:/usr/src/app/index.js
      - ${PWD}/log-aggregator/logs:/logs
    networks:
      - hotspotplusgate
  dashboard:
    build:
      context: ${PWD}/dashboard
    user: '${UID:-1000}:${GID:-1000}'
    restart: always
    ports:
      - 8080:8080
    command: npm start
    volumes:
      - ${PWD}/dashboard/src:/usr/src/app/src
      - ${PWD}/dashboard/libs:/usr/src/app/libs
      - ${PWD}/dashboard/node_modules:/usr/src/app/node_modules
      - ${PWD}/dashboard/logs:/logs
    networks:
      - hotspotplusgate
  cordinator:
    build:
      context: ${PWD}/cordinator
    user: '${UID:-1000}:${GID:-1000}'
    restart: always
    depends_on:
      - redis
    environment:
      - APP_NAME=cordinator
      - LOG_LEVEL=debug
      - LOG_DIR=/logs
      - REDIS_PORT=6379
      - REDIS_HOST=hsp_redis
      - REDIS_IP=hsp_redis
    volumes:
      - ${PWD}/cordinator/hotspotplus-cordinator:/app/hotspotplus-cordinator
      - ${PWD}/cordinator/logs:/logs
      - ${PWD}/systemId:/systemId
    networks:
      - hotspotplusgate
  mongodb:
    container_name: hsp_mongodb
    image: bitnami/mongodb:3.6.8-ol-7-r100
    restart: always
    volumes:
      - hsp_mongodb:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hotspotplusgate
  redis:
    image: bitnami/redis:4.0.12-debian-9-r11
    container_name: hsp_redis
    restart: always
    volumes:
      - hsp_redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hotspotplusgate
  elasticsearch:
    container_name: hsp_elasticsearch
    image: 'bitnami/elasticsearch:5.3.0-r0'
    restart: always
    expose:
      - "9300"
      - "9200"
    volumes:
      - hsp_elasticsearch:/bitnami/elasticsearch
    networks:
      - hotspotplusgate
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: always
    container_name: 'hsp_zookeeper'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    expose:
      - '2181'
    networks:
      - hotspotplusgate
  kafka:
    image: 'bitnami/kafka:latest'
    restart: always
    container_name: 'hsp_kafka'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://hsp_kafka:9092
      - KAFKA_LOG_RETENTION_HOURS=72
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=hsp_zookeeper:2181
    expose:
      - '9092'
    volumes:
      - hsp_kafka:/bitnami/kafka
    networks:
      - hotspotplusgate
  radius:
    image: 'registry.gitlab.com/parmenides/hspfreeradius/production:3.3'
    restart: always
    env_file:
      .env
    container_name: "hsp_radius_production"
    networks:
      - hotspotplusgate
    expose:
      - "1812"
      - "1813"
    ports:
      - "$RADIUS_AUTH_PORT:1812/udp"
      - "$RADIUS_ACC_PORT:1813/udp"

volumes:
  hsp_mongodb:
    driver: local
  hsp_redis:
    driver: local
  hsp_elasticsearch:
    driver: local
  hsp_kafka:
    driver: local

networks:
  hotspotplusgate:
    external: true
