version: '3.6'
services:
  hotspotplusapi:
    image: 'hotspotplus_hotspotplusapi'
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ${PWD}/systemId:/systemId
      - ${PWD}/api/server:/usr/src/app/server/
      - ${PWD}/files:/files
      - ${PWD}/api/node_modules:/usr/src/app/node_modules
      - ${PWD}/api/common:/usr/src/app/common/
      - ${PWD}/api/logs:/logs
      - ${PWD}/api/key:/key
    networks:
      - hotspotplusgate
  hotspotpluslicensapi:
    image: 'hotspotplus_hotspotpluslicensapi'
    command: npm run start:dev
    ports:
      - 3001:3000
    depends_on:
      - mongodb
#      - elasticsearch
      - redis
    volumes:
      - ${PWD}/api-license/server:/usr/src/app/server/
      - ${PWD}/api-license/node_modules:/usr/src/app/node_modules
      - ${PWD}/api-license/common:/usr/src/app/common/
      - ${PWD}/api-license/logs:/logs
      - ${PWD}/api-license/key:/key
    networks:
      - hotspotplusgate
  mongodb:
    image: bitnami/mongodb:3.6.8-ol-7-r100
    volumes:
      - hsp_mongodb:/bitnami
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hotspotplusgate
  redis:
    image: bitnami/redis:4.0.12-debian-9-r11
    volumes:
      - hsp_redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - hotspotplusgate
  clickhouse:
    image: yandex/clickhouse-server
    hostname: clickhouse
    ports:
    - 9000:9000
    - 9009:9009
    - 8123:8123
    volumes:
    - ./clickhouse/clickhouse_config.xml:/etc/clickhouse-server/config.xml
    - ./clickhouse/clickhouse_metrika.xml:/etc/clickhouse-server/metrika.xml
    - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
    -  clickhouse:/var/lib/clickhouse
    networks:
      hotspotplusgate:
        ipv4_address: 172.20.0.85
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - hotspotplusgate
  kafka:
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LOG_RETENTION_HOURS=72
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=hsp_zookeeper:2181
    networks:
      hotspotplusgate:
        ipv4_address: 172.20.0.80
  radius:
    image: 'registry.gitlab.com/parmenides/hspfreeradius/production:3.3'
    networks:
      - hotspotplusgate
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"


volumes:
  hsp_grafana:
    driver: local
  hsp_mongodb:
    driver: local
  hsp_redis:
    driver: local
  kafka:
    driver: local
  clickhouse:
    driver: local

networks:
   hotspotplusgate:


