version: '3'
services:
  accountinglogstash:
    image: 'docker.elastic.co/logstash/logstash:7.1.1'
    restart: always
    environment:
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/accounting.conf:/usr/share/logstash/pipeline/accounting.conf
    networks:
      - hotspotplusgate

networks:
  hotspotplusgate:
    external: true
