version: '3'
services:
  netflowlog:
    image: 'docker.elastic.co/logstash/logstash:6.5.4'
    restart: always
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - hotspotplusgate
  syslog:
    image: 'docker.elastic.co/logstash/logstash:6.5.4'
    restart: always
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    volumes:
      - ./syslog:/usr/share/logstash/pipeline/
    networks:
      - hotspotplusgate
  accountinglogstash:
    image: 'docker.elastic.co/logstash/logstash:6.5.4'
    restart: always
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    volumes:
      - ./accounting/:/usr/share/logstash/pipeline/
    networks:
      - hotspotplusgate

networks:
  hotspotplusgate:
    external: true
